version: '3.1'

# This file may be used for local development of DTT. It is not used by CircleCI.
# This file mimics the environment that CircleCI uses to test DTT (tests/config.yml).
services:
  drupal:
    image: "massgov/drupal-container:1.0.6-dev"
    volumes:
      # Non OSX users may want to set VOLUME_FLAGS via the .env file.
      - ..:/var/www/code:${VOLUME_FLAGS-cached}
    environment:
      - APACHE_DOCROOT=/var/www/code/web
      - DTT_BASE_URL=http://127.0.0.1
      - XDEBUG_ENABLE
      - XDEBUG_CONFIG
      # Suggested by https://confluence.jetbrains.com/display/PhpStorm/Debugging+PHP+CLI+scripts+with+PhpStorm#DebuggingPHPCLIscriptswithPhpStorm-2.StarttheScriptwithDebuggerOptions
      # Create a PHP Server in PHPStorm called 'dtt'. Then add path mappings during first debug session.
      - PHP_IDE_CONFIG=serverName=dtt
    working_dir: /var/www/code
    ports:
      #Expose port 81 by default since that collides less frequently.
      #Define WEB_PORT in a .env file to change to a different port.
      - '${WEB_PORT-81}:80'

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_USER: circle
      MYSQL_PASSWORD: circle
      MYSQL_DATABASE: circle
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    command: --max_allowed_packet=32M --innodb_flush_method=O_DIRECT --tmp_table_size=16M --query_cache_size=16M --innodb-flush-log-at-trx-commit=2  --innodb_buffer_pool_size=500M --innodb_log_buffer_size=64M --skip-innodb_doublewrite --innodb_log_file_size=64M
    ports:
      - '3106:3306'