version: 2

jobs:
  build:
    working_directory: /var/www/code
    docker:
      # @see https://github.com/massgov/Drupal-Container
      - image: massgov/drupal-container:1.0.6-ci
        environment:
          COMPOSER_ALLOW_SUPERUSER: 1
          DTT_BASE_URL: http://127.0.0.1
          APACHE_DOCROOT: /var/www/code/web
      - image: mariadb
        environment:
          MYSQL_USER: circle
          MYSQL_PASSWORD: circle
          MYSQL_DATABASE: circle
          MYSQL_RANDOM_ROOT_PASSWORD: 1
        command: --max_allowed_packet=32M --innodb_flush_method=O_DIRECT --tmp_table_size=16M --query_cache_size=16M --innodb-flush-log-at-trx-commit=2  --innodb_buffer_pool_size=500M --innodb_log_buffer_size=64M --skip-innodb_doublewrite --innodb_log_file_size=64M
    steps:
      - checkout
      - run: echo 'export PATH=/var/www/code/vendor/bin:$PATH' >> $BASH_ENV
      - run: composer install -n --prefer-dist
      - run: vendor/bin/parallel-lint src tests
      - run: vendor/bin/phpcs --report-full
      - run: {name: 'Start Apache', command: '/usr/local/bin/apache2-foreground-enhanced', background: true}
      - run: drush si -yv --db-url=mysql://circle:circle@127.0.0.1/circle standard
      - run: phpunit --bootstrap=web/core/tests/bootstrap.php tests
